from manim import *

def gradientWhiteColor(n):
    return ImageMobject(np.uint8([[i * 256 / n for i in range(0, n)] for _ in range(0, n)]))    
    
class Index(Scene):
    def construct(self):
        congthuc = Dot(color=YELLOW)
        self.play(FadeIn(congthuc))
        circle1 = Circle(radius=0.6, color=WHITE).shift(LEFT*3 + UP*3).set_fill(PINK, opacity=0.5)
        circle2 = Circle(radius=0.6, color=WHITE).shift(RIGHT*2 + UP*2).set_fill(PINK, opacity=0.5)
        circle3 = Circle(radius=0.6, color=WHITE).shift(LEFT*3 + UP*1).set_fill(PINK, opacity=0.5)
        circle4 = Circle(radius=0.6, color=WHITE).shift(RIGHT*2).set_fill(PINK, opacity=0.5)
        circle5 = Circle(radius=0.6, color=WHITE).shift(LEFT*3 + DOWN*1).set_fill(PINK, opacity=0.5)
        circle6 = Circle(radius=0.6, color=WHITE).shift(RIGHT*2 + DOWN*2).set_fill(PINK, opacity=0.5)
        self.play(FadeIn(circle1, circle2, circle3, circle4, circle5, circle6))
        self.play(congthuc.animate.move_to(circle1, LEFT+RIGHT+UP+DOWN), run_time=0.5)
        self.play(congthuc.animate.move_to(circle2, LEFT+RIGHT+UP+DOWN), circle1.animate.set_fill(BLUE, opacity=0.5), run_time=0.5)
        self.play(congthuc.animate.move_to(circle3, LEFT+RIGHT+UP+DOWN), circle2.animate.set_fill(BLUE, opacity=0.5), run_time=0.5)
        self.play(congthuc.animate.move_to(circle4, LEFT+RIGHT+UP+DOWN), circle3.animate.set_fill(BLUE, opacity=0.5), run_time=0.5)
        self.play(congthuc.animate.move_to(circle5, LEFT+RIGHT+UP+DOWN), circle4.animate.set_fill(BLUE, opacity=0.5), run_time=0.5)
        self.play(congthuc.animate.move_to(circle6, LEFT+RIGHT+UP+DOWN), circle5.animate.set_fill(BLUE, opacity=0.5), run_time=0.5)
        self.play(circle6.animate.set_fill(BLUE, opacity=0.5), run_time=0.5)

        self.play(FadeOut(congthuc))
        catch = Group(Rectangle(width=1.5, height=0.1), Rectangle(width=0.85, height=0.05).shift(DOWN*0.1)).shift(DOWN*(4-0.15)+LEFT*8)
        self.play(FadeIn(catch))
        self.play(catch.animate.shift(RIGHT*10))
        self.wait(0.5)
        self.play(circle6.animate.shift(DOWN*5), run_time=1)
        self.play(catch.animate.shift(LEFT*5))
        self.wait(0.5)
        self.play(circle5.animate.shift(DOWN*6), run_time=1)
        self.play(catch.animate.shift(RIGHT*5))
        self.wait(0.5)
        self.play(circle4.animate.shift(DOWN*6), run_time=1)
        self.play(catch.animate.shift(LEFT*5))
        self.wait(0.5)
        self.play(circle3.animate.shift(DOWN*7), run_time=1)
        self.play(catch.animate.shift(RIGHT*5))
        self.wait(0.5)
        self.play(circle2.animate.shift(DOWN*7), run_time=1)
        self.play(catch.animate.shift(LEFT*5))
        self.wait(0.5)
        self.play(circle1.animate.shift(DOWN*8), run_time=1)
        self.wait(0.5)
        self.play(catch.animate.shift(RIGHT*11))
        self.wait(3)

        line2 = Line([-12, 0, 0], [12, 0, 0]).shift(UP*3)
        line3 = Line([-12, 0, 0], [12, 0, 0]).shift(UP*1)
        clickcircle = Circle(radius=0.7, color=GRAY).shift(UP*2 + LEFT*5)
        self.play(Create(line2), Create(line3), FadeIn(clickcircle))
    
        taiko1 = Circle(radius=0.7, color=WHITE).shift(UP*2 + RIGHT*12).set_fill(RED, opacity=1)
        taiko2 = Circle(radius=0.5, color=WHITE).shift(UP*2 + RIGHT*12).set_fill(RED, opacity=1)
        taiko3 = Circle(radius=0.5, color=WHITE).shift(UP*2 + RIGHT*12).set_fill(BLUE, opacity=1)
        taiko4 = Circle(radius=0.5, color=WHITE).shift(UP*2 + RIGHT*12).set_fill(RED, opacity=1)
        taiko5 = Circle(radius=0.7, color=WHITE).shift(UP*2 + RIGHT*12).set_fill(BLUE, opacity=1)
        taiko6 = Circle(radius=0.7, color=WHITE).shift(UP*2 + RIGHT*12).set_fill(BLUE, opacity=1)

        self.play(FadeIn(taiko1, taiko2, taiko3, taiko4, taiko5, taiko6))
        self.play(taiko1.animate.shift(LEFT * 17))
        self.play(clickcircle.animate.set_fill(RED, opacity=0.4), run_time=0.1)
        self.play(taiko1.animate.shift(UP * 7), run_time=0.3)
        self.play(clickcircle.animate.set_fill(RED, opacity=0), run_time=0.1)
        self.play(taiko2.animate.shift(LEFT * 17))
        self.play(clickcircle.animate.set_fill(RED, opacity=0.4), run_time=0.1)
        self.play(taiko2.animate.shift(UP * 7), run_time=0.3)
        self.play(clickcircle.animate.set_fill(RED, opacity=0), run_time=0.1)
        self.play(taiko3.animate.shift(LEFT * 17))
        self.play(clickcircle.animate.set_fill(BLUE, opacity=0.4), run_time=0.1)
        self.play(taiko3.animate.shift(UP * 7), run_time=0.3)
        self.play(clickcircle.animate.set_fill(BLUE, opacity=0), run_time=0.1)
        self.play(taiko4.animate.shift(LEFT * 17))
        self.play(clickcircle.animate.set_fill(RED, opacity=0.4), run_time=0.1)
        self.play(taiko4.animate.shift(UP * 7), run_time=0.3)
        self.play(clickcircle.animate.set_fill(RED, opacity=0), run_time=0.1)
        self.play(taiko5.animate.shift(LEFT * 17))
        self.play(clickcircle.animate.set_fill(BLUE, opacity=0.4), run_time=0.1)
        self.play(taiko5.animate.shift(UP * 7), run_time=0.3)
        self.play(clickcircle.animate.set_fill(BLUE, opacity=0), run_time=0.1)
        self.play(taiko6.animate.shift(LEFT * 17))
        self.play(clickcircle.animate.set_fill(BLUE_D, opacity=0.4), run_time=0.1)
        self.play(taiko6.animate.shift(UP * 7), run_time=0.3)
        self.play(clickcircle.animate.set_fill(BLUE, opacity=0), run_time=0.1)
        self.wait(1)
        self.play(FadeOut(clickcircle, line2, line3))
        self.wait(3)

        mania1 = Rectangle(width=1, height=0.35).set_fill(PINK, 0.7).shift(UP*7+RIGHT*3)
        mania2 = Rectangle(width=1, height=0.35).set_fill(WHITE, 0.7).shift(UP*7+RIGHT*2)
        mania3 = Rectangle(width=1, height=0.35).set_fill(PINK, 0.7).shift(UP*7+RIGHT)
        mania4 = Rectangle(width=1, height=0.35).set_fill(PINK, 0.7).shift(UP*7+LEFT)
        mania5 = Rectangle(width=1, height=0.35).set_fill(PINK, 0.7).shift(UP*7+3*LEFT)
        mania6 = Rectangle(width=1, height=0.35).set_fill(YELLOW, 0.7).shift(UP*7)
        mania7 = Rectangle(width=1, height=0.35).set_fill(WHITE, 0.7).shift(UP*7+RIGHT*2)
        mania8 = Rectangle(width=1, height=0.35).set_fill(PINK, 0.7).shift(UP*7+RIGHT)
        mania9 = Rectangle(width=1, height=0.35).set_fill(YELLOW, 0.7).shift(UP*7)
        mania10 = Rectangle(width=1, height=0.35).set_fill(PINK, 0.7).shift(UP*7+RIGHT*3)
        mania11 = Rectangle(width=1, height=0.35).set_fill(WHITE, 0.7).shift(UP*7+2*LEFT)
        mania12 = Rectangle(width=1, height=0.35).set_fill(PINK, 0.7).shift(UP*7+3*LEFT)
        mania13 = Rectangle(width=1, height=0.35).set_fill(PINK, 0.7).shift(UP*7+RIGHT)
        mania14 = Rectangle(width=1, height=0.35).set_fill(WHITE, 0.7).shift(UP*7+2*LEFT)

        maniaclick1 = Rectangle(width=1, height=2).set_fill(PINK, 1).shift(DOWN * 7)
        maniaclick2 = Rectangle(width=1, height=2).set_fill(WHITE, 1).shift(DOWN * 7)
        maniaclick3 = Rectangle(width=1, height=2).set_fill(PINK, 1).shift(DOWN * 7)
        maniaclick4 = Rectangle(width=1, height=2).set_fill(YELLOW, 1).shift(DOWN * 7)
        maniaclick5 = Rectangle(width=1, height=2).set_fill(PINK, 1).shift(DOWN * 7)
        maniaclick6 = Rectangle(width=1, height=2).set_fill(WHITE, 1).shift(DOWN * 7)
        maniaclick7 = Rectangle(width=1, height=2).set_fill(PINK, 1).shift(DOWN * 7)

        line4 = Line([0, 10, 0], [0, -10, 0]).shift(LEFT*3.5)
        line5 = Line([0, 10, 0], [0, -10, 0]).shift(RIGHT*3.5)

        image = gradientWhiteColor(256).rotate(-PI/2)
        image.width = 3
        image.height = 1
        
        light1 = image.copy().shift(DOWN*2.5 + LEFT*3)
        light2 = image.copy().shift(DOWN*2.5 + LEFT*2)
        light3 = image.copy().shift(DOWN*2.5 + LEFT*1)
        light4 = image.copy().shift(DOWN*2.5)
        light5 = image.copy().shift(DOWN*2.5 + RIGHT*1)
        light6 = image.copy().shift(DOWN*2.5 + RIGHT*2)
        light7 = image.copy().shift(DOWN*2.5 + RIGHT*3)

        self.play(FadeIn(maniaclick1, maniaclick2, maniaclick3, maniaclick4, maniaclick5, maniaclick6, maniaclick7))
        self.play(maniaclick1.animate.shift(UP*3), maniaclick2.animate.shift(UP*3), maniaclick3.animate.shift(UP*3), maniaclick4.animate.shift(UP*3), maniaclick5.animate.shift(UP*3), maniaclick6.animate.shift(UP*3), maniaclick7.animate.shift(UP*3))
        self.play(maniaclick1.animate.shift(LEFT*3), maniaclick2.animate.shift(LEFT*2), maniaclick3.animate.shift(LEFT), maniaclick5.animate.shift(RIGHT), maniaclick6.animate.shift(RIGHT*2), maniaclick7.animate.shift(RIGHT*3))
        self.play(Create(line4), Create(line5))

        self.play(mania1.animate.next_to(maniaclick7, DOWN), FadeIn(light7), run_time=0.5)
        self.play(mania2.animate.next_to(maniaclick6, DOWN), FadeIn(light6), FadeOut(light7), run_time=0.5)
        self.play(mania3.animate.next_to(maniaclick5, DOWN), FadeIn(light5), FadeOut(light6), run_time=0.5)
        self.play(mania4.animate.next_to(maniaclick3, DOWN), FadeIn(light3), FadeOut(light5), run_time=0.5)
        self.play(mania5.animate.next_to(maniaclick1, DOWN), FadeIn(light1), FadeOut(light3), run_time=0.5)
        self.play(mania6.animate.next_to(maniaclick4, DOWN), FadeIn(light4), FadeOut(light1), run_time=0.5)
        self.play(mania7.animate.next_to(maniaclick6, DOWN), FadeIn(light6), FadeOut(light4), run_time=0.5)
        self.play(mania8.animate.next_to(maniaclick5, DOWN), FadeIn(light5), FadeOut(light6), run_time=0.5)
        self.play(mania9.animate.next_to(maniaclick4, DOWN), FadeIn(light4), FadeOut(light5), run_time=0.5)
        self.play(mania10.animate.next_to(maniaclick7, DOWN), FadeIn(light7), FadeOut(light4), run_time=0.5)
        self.play(mania11.animate.next_to(maniaclick2, DOWN), FadeIn(light2), FadeOut(light7), run_time=0.5)
        self.play(mania12.animate.next_to(maniaclick1, DOWN), FadeIn(light1), FadeOut(light2), run_time=0.5)
        self.play(mania13.animate.next_to(maniaclick5, DOWN), FadeIn(light5), FadeOut(light1), run_time=0.5)
        self.play(mania14.animate.next_to(maniaclick2, DOWN), FadeIn(light2), FadeOut(light5), run_time=0.5)
        self.play(FadeOut(light2), run_time=0.5)
        self.wait(2)
        self.play(FadeOut(line4, line5))
        self.play(maniaclick1.animate.shift(RIGHT*3), maniaclick2.animate.shift(RIGHT*2), maniaclick3.animate.shift(RIGHT), maniaclick5.animate.shift(LEFT), maniaclick6.animate.shift(LEFT*2), maniaclick7.animate.shift(LEFT*3))
        self.play(maniaclick1.animate.shift(DOWN*3), maniaclick2.animate.shift(DOWN*3), maniaclick3.animate.shift(DOWN*3), maniaclick4.animate.shift(DOWN*3), maniaclick5.animate.shift(DOWN*3), maniaclick6.animate.shift(DOWN*3), maniaclick7.animate.shift(DOWN*3))
        self.wait(3)